
void main() {

try{

int x = 5 ~/ 0;

} catch (a,b){
print('Exception is :~ $a');
print('Stack Trace :~ $b');
}

}


/*
 "a" is a Exception Object Which
 Stores the Exception
Generated By The Program.

"b" is a Stack Trace Object 
Which Stores the Stack Trace 
Generated by The Program.

Note :~ We Can Use Any variable
to store that Exception and Stack
Trace , Like a,b,c,x,y,z etc.
*/

/* Catch Clause is Used
When We Don't know What will be
the Error/Exception. */
