
void main() {

try{

int x = 5 ~/ 0;

} catch (a){
print('Exception is :~ $a');
} finally{
print("Finally Clause........");
}

}



/* Finally  Clause is Used
to Ensure That Program Has 
Executed or Not.*/
